# ======
# Project Details
# ======
config-version: 2
name: 'dbt_market_calendar'
version: '0.0.1'
profile: default

# ======
# File Path Configs
# ======
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

# ======
# Seed Configs
# ======
seeds:
  dbt_market_calendar:
    +enabled: true
    +materialized: table
    +schema: calendar
    +quote_columns: False
    +column_types:
        row_index: numeric
        row_date: Date
        row_year: numeric
        row_month: numeric
        row_yearmonth: string
        row_day: numeric
        row_week_index: numeric
        row_day_index: numeric
        is_weekend: numeric
        is_market_holiday: numeric
        is_eq_weekly_exp: numeric
        eq_weekly_exp_cumulative: numeric
        is_eq_monthly_exp: numeric
        is_eq_quarterly_exp: numeric
        is_vix_weekly_exp: numeric
        vix_weekly_exp_cumulative: numeric
        is_vix_monthly_exp: numeric
        is_vix_quarterly_exp: numeric

# ======
# Model Configs
# ======
models:
  dbt_market_calendar:
    +enabled: true
    +materialized: table
    +schema: calendar